---
title: "p8105_hw3_jw4489"
output: github_document
date: "2023-10-12"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

##### Look at data.

```{r}
library(p8105.datasets)
data("instacart")

instacart = 
  instacart |> 
  as_tibble()

instacart
```



## Problem 2

###### Look at data and do some data cleaning.

```{r}
data("brfss_smart2010")

brfss = 
  brfss_smart2010 |> 
  janitor::clean_names() |>
  filter(
    topic == "Overall Health",
    response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")
    ) |>
  mutate(
    response = factor(response, levels = c("Poor", "Fair", "Good", "Very good", "Excellent"), ordered = TRUE)
    )

brfss
```








